# Generated by Django 6.0.5 on 2026-06-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_category_is_default_developer_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_assignment', 'New Assignment'), ('reassignment', 'Reassignment'), ('upcoming_delivery', 'Upcoming Delivery'), ('overdue', 'Overdue'), ('qa_rejection', 'QA Rejection'), ('completed', 'Issue Completed')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='issues.issue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
