# Generated by Django 6.0.5 on 2026-07-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='summary',
            new_name='task_name',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='module',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
