# Generated by Django 6.0.5 on 2026-07-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_rename_summary_issue_task_name_issue_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='notes',
            new_name='developer_comments',
        ),
        migrations.AddField(
            model_name='issue',
            name='qa_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='delivery_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.deliverystatus'),
        ),
    ]
