# Generated by Django 6.0.5 on 2026-07-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_deliverystatus_rename_notes_issue_developer_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='qa_by',
        ),
        migrations.AddField(
            model_name='issue',
            name='qa_by',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues.qamember'),
        ),
    ]
