# Generated by Django 6.0.5 on 2026-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_qamember_remove_issue_qa_by_issue_qa_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_assignment', 'New Assignment'), ('reassignment', 'Reassignment'), ('upcoming_delivery', 'Upcoming Delivery'), ('overdue', 'Overdue'), ('qa_rejection', 'QA Rejection'), ('qa_approval', 'QA Approval'), ('closure', 'Issue Completed'), ('reopened', 'Issue Reopened'), ('dev_comment', 'Developer Comment'), ('qa_comment', 'QA Comment'), ('delivered', 'Issue Delivered')], max_length=50),
        ),
    ]
