# Generated by Django 6.0.5 on 2026-07-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_assignment', 'New Assignment'), ('reassignment', 'Reassignment'), ('upcoming_delivery', 'Upcoming Delivery'), ('overdue', 'Overdue'), ('qa_rejection', 'QA Rejection'), ('qa_approval', 'QA Approval'), ('completed', 'Issue Completed'), ('reopened', 'Issue Reopened'), ('dev_comment', 'Developer Comment'), ('qa_comment', 'QA Comment'), ('delivered', 'Issue Delivered')], max_length=30),
        ),
    ]
