# Generated by Django 6.0.6 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_notification_options_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('developer', 'Developer'), ('qa', 'QA')], max_length=20)),
                ('external_id', models.CharField(blank=True, help_text="Reserved for the future external API's user ID.", max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_profile', to='issues.appuser'),
        ),
        migrations.CreateModel(
            name='IssueAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='issues.developer')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='issues.issue')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]