# Generated by Django 6.0.6 on 2026-07-16
#
# Consolidates onto the accounts app's AppUser (the pre-existing, more
# complete "login as" system) instead of the duplicate AppUser that was
# temporarily added to the issues app in migration 0009. This drops the
# issues_appuser table (any AppUsers created there for testing purposes
# are lost) and repoints Developer.linked_user at accounts.AppUser.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_developer_role'),
        ('issues', '0009_appuser_developer_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='linked_user',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.AddField(
            model_name='developer',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_profile', to='accounts.appuser'),
        ),
    ]