# Generated by Django 6.0.6 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_reconcile_appuser_with_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='approx_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]