# Generated by Django 6.0.6 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_approx_delivery_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='qa_by',
        ),
        migrations.AddField(
            model_name='issue',
            name='qa_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='issues.qamember',
            ),
        ),
        migrations.CreateModel(
            name='QAAssignmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_assignment_history', to='issues.issue')),
                ('qa_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='issues.qamember')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]