# Generated by Django 6.0.6 on 2026-07-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_qa_role'),
        ('issues', '0012_qa_by_fk_qaassignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='qamember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qamember',
            name='linked_user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='qa_profile',
                to='accounts.appuser',
            ),
        ),
    ]