# Generated by Django 6.0.6 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_business_analyst_role'),
        ('issues', '0013_qamember_linked_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='accounts.appuser',
            ),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='accounts.appuser',
            ),
        ),
    ]