# Generated by Django 6.0.6 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def populate_created_by(apps, schema_editor):
    """
    Best-effort backfill: reported_by was free text, so we match it
    against AppUser.name where possible. Any issue whose reported_by
    doesn't match a real AppUser (e.g. it was typed differently, or the
    user has since been renamed/removed) is left with created_by=None
    rather than guessing - it can be corrected manually afterward.
    """
    Issue = apps.get_model('issues', 'Issue')
    AppUser = apps.get_model('accounts', 'AppUser')

    name_to_user = {u.name: u for u in AppUser.objects.all()}
    for issue in Issue.objects.exclude(reported_by=''):
        user = name_to_user.get(issue.reported_by)
        if user is not None:
            issue.created_by = user
            issue.save(update_fields=['created_by'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_business_analyst_role'),
        ('issues', '0014_add_created_by_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reported_issues',
                to='accounts.appuser',
            ),
        ),
        migrations.RunPython(populate_created_by, noop_reverse),
    ]