# Generated by Django 6.0.6 on 2026-07-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0015_issue_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='reported_by',
        ),
    ]