# Generated by Django 6.0.5 on 2026-07-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_remove_issue_reported_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='issue',
            name='qa_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.qamember'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_assignment', 'New Assignment'), ('reassignment', 'Reassignment'), ('upcoming_delivery', 'Upcoming Delivery'), ('overdue', 'Overdue'), ('qa_rejection', 'QA Rejection'), ('qa_approval', 'QA Approval'), ('completed', 'Issue Completed'), ('reopened', 'Issue Reopened'), ('dev_comment', 'Developer Comment'), ('qa_comment', 'QA Comment'), ('delivered', 'Issue Delivered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='qaassignmenthistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
