# Generated by Django 6.0.6 on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_role_permissions_alter_appuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('developer', 'Developer')], max_length=30),
        ),
    ]