# Generated by Django 6.0.6 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_developer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('developer', 'Developer'), ('qa', 'QA')], max_length=30),
        ),
    ]