# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_business_analyst_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('developer', 'Developer'), ('qa', 'QA'), ('business_analyst', 'Business Analyst'), ('management', 'Management')], max_length=30),
        ),
    ]