# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_management_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('developer', 'Developer'), ('qa', 'QA'), ('business_analyst', 'Business Analyst'), ('management', 'Management')], default='', help_text='Blank means the user currently has no role assigned.', max_length=30),
        ),
    ]